/* Generates the hard-coded 169x169 preflop equity table.
 * Run: npx ts-node scripts/gen-preflop-equity.ts [simsPerMatchup]
 * Writes src/services/poker/preflopEquity.generated.ts (PREFLOP_WIN, PREFLOP_TIE,
 * flat 169*169 arrays, win% and tie% for the row hand vs the column hand).
 *
 * Each matchup re-randomizes both hands' suits and the 5-card runout every sim,
 * so the stored value is the hand-TYPE average over all suit configurations.
 */
import * as fs from 'fs';
import * as path from 'path';
import { Card } from '../src/types';
import { createDeck, shuffleDeck } from '../src/services/poker/cards';
import { compareHands } from '../src/services/poker/handEvaluator';
import { ALL_NOTATIONS, N_TYPES, combosOf } from '../src/services/poker/preflopCanonical';

const SIMS = Math.max(200, parseInt(process.argv[2] || '4000', 10));
console.log(`Generating ${N_TYPES}x${N_TYPES} preflop equity table @ ${SIMS} sims/matchup...`);

const combos = ALL_NOTATIONS.map(combosOf);
const fullDeck = createDeck();
const round1 = (n: number) => Math.round(n * 10) / 10;

const WIN = new Array(N_TYPES * N_TYPES).fill(0);
const TIE = new Array(N_TYPES * N_TYPES).fill(0);

const t0 = Date.now();
let done = 0;
const totalMatchups = (N_TYPES * (N_TYPES + 1)) / 2;

for (let i = 0; i < N_TYPES; i++) {
  const ci = combos[i];
  for (let j = i; j < N_TYPES; j++) {
    const cj = combos[j];
    let wi = 0, wj = 0, t = 0, valid = 0;

    for (let s = 0; s < SIMS; s++) {
      const h1 = ci[(Math.random() * ci.length) | 0];
      const h2 = cj[(Math.random() * cj.length) | 0];
      // Reject if the two hands share a card (e.g. AKs vs AQs both Ah).
      if (h1[0] === h2[0] || h1[0] === h2[1] || h1[1] === h2[0] || h1[1] === h2[1]) continue;

      const used = new Set<string>([h1[0], h1[1], h2[0], h2[1]]);
      const deck = shuffleDeck(fullDeck);
      const board: Card[] = [];
      for (let d = 0; d < deck.length && board.length < 5; d++) {
        if (!used.has(deck[d])) board.push(deck[d]);
      }
      const r = compareHands([h1[0], h1[1], ...board], [h2[0], h2[1], ...board]);
      if (r === 1) wi++; else if (r === -1) wj++; else t++;
      valid++;
    }

    const denom = valid || 1;
    const wiPct = round1((wi / denom) * 100);
    const wjPct = round1((wj / denom) * 100);
    const tPct = round1((t / denom) * 100);

    WIN[i * N_TYPES + j] = wiPct; TIE[i * N_TYPES + j] = tPct;
    WIN[j * N_TYPES + i] = wjPct; TIE[j * N_TYPES + i] = tPct;

    done++;
  }
  if (i % 13 === 0) {
    const pct = ((done / totalMatchups) * 100).toFixed(0);
    const elapsed = ((Date.now() - t0) / 1000).toFixed(0);
    console.log(`  row ${i + 1}/${N_TYPES} — ${pct}% — ${elapsed}s`);
  }
}

const outPath = path.join(__dirname, '..', 'src', 'services', 'poker', 'preflopEquity.generated.ts');
const header = `// AUTO-GENERATED by scripts/gen-preflop-equity.ts (${SIMS} sims/matchup). Do not edit.
// Flat ${N_TYPES}x${N_TYPES} tables: index = row*${N_TYPES} + col. Values are percentages.
`;
const body =
  `export const PREFLOP_WIN: number[] = [${WIN.join(',')}];\n` +
  `export const PREFLOP_TIE: number[] = [${TIE.join(',')}];\n`;
fs.writeFileSync(outPath, header + body);

console.log(`Done in ${((Date.now() - t0) / 1000).toFixed(0)}s → ${outPath}`);
